version: '2'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123qweASD
      - MYSQL_PASSWORD=123qweASD
      - MYSQL_DATABASE=lanbox
      - MYSQL_USER=lanbox

  redis:
    image: redis
    restart: always

  app:
    image: mchus/lanbox-app
    restart: always
    volumes:
      - app:/var/www/html
      - data:/var/www/html/data
    environment:
      - MYSQL_HOST=db
      - MYSQL_ROOT_PASSWORD=123qweASD
      - MYSQL_PASSWORD=123qweASD
      - MYSQL_DATABASE=lanbox
      - MYSQL_USER=lanbox
    depends_on:
      - db
      - redis

  static:
    image: mchus/lanbox-static
    restart: always
    volumes:
      - app:/var/www/html:ro
      - data:/var/www/html/data:ro
    environment:
      - SRV_ADDRESS="app"
      - SRV_PORT="9000"
    depends_on:
      - app
  cron:
    image: mchus/lanbox-cron
    restart: always
    volumes:
      - app:/var/www/html
    depends_on:
      - db
      - redis

volumes:
  db:
  app:
  certs:
  data:
