name: LanBox server
description: Enterprise File Sync and Share
version: 0.0.2
category: File Synchronisation
maintainer: Mikhail Chusavitin (chusavitin@lanit.ru)
license: # The license
projectURL: # The URL related to the Catalog entry
