apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --controller deployment
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: db
    spec:
      containers:
      - args:
        - --transaction-isolation=READ-COMMITTED
        - --binlog-format=ROW
        env:
        - name: MYSQL_DATABASE
          value: lanbox
        - name: MYSQL_PASSWORD
          value: 123qweASD
        - name: MYSQL_ROOT_PASSWORD
          value: 123qweASD
        - name: MYSQL_USER
          value: lanbox
        image: mariadb
        name: db
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: db
      restartPolicy: Always
      volumes:
      - name: db
        persistentVolumeClaim:
          claimName: db
status: {}
