apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --controller deployment
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: static
  name: static
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: static
    spec:
      containers:
      - env:
        - name: SRV_ADDRESS
          value: '"app"'
        - name: SRV_PORT
          value: '"9000"'
        image: mchus/lanbox-static
        name: static
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /var/www/html
          name: app
        - mountPath: /var/www/html/data
          name: data
      restartPolicy: Always
      volumes:
      - name: app
        persistentVolumeClaim:
          claimName: app
      - name: data
        persistentVolumeClaim:
          claimName: data
status: {}
