apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --controller deployment
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: static
  name: static
spec:
  ports:
  - name: "9999"
    port: 9999
    targetPort: 80
  selector:
    io.kompose.service: static
status:
  loadBalancer: {}
